# Generated by Django 2.0 on 2019-11-07 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.IntegerField(blank=True, max_length=30, null=True, verbose_name='电话')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '关于公司',
                'verbose_name_plural': '关于公司',
            },
        ),
    ]
