# Generated by Django 2.0 on 2019-11-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='电话'),
        ),
    ]
