# Generated by Django 2.0 on 2019-11-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191107_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address_code',
            field=models.CharField(default='', max_length=100, verbose_name='英文地址'),
        ),
    ]
