# Generated by Django 2.0 on 2019-11-11 13:59

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('name_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='英文名')),
                ('brief', models.TextField(default='', max_length=300, verbose_name='简短描述')),
                ('brief_code', models.TextField(default='', max_length=300, verbose_name='简短英文描述')),
                ('desc', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('desc_code', DjangoUeditor.models.UEditorField(default='', verbose_name='英文内容')),
                ('company_front_image', models.ImageField(blank=True, null=True, upload_to='company/images/', verbose_name='封面图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '企业',
                'verbose_name_plural': '企业',
            },
        ),
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('name_code', models.CharField(default='', max_length=30, verbose_name='英文名')),
                ('category_rank', models.IntegerField(choices=[(1, '一级类别'), (2, '二级类别')], default=1, verbose_name='类别级别')),
                ('category_type', models.CharField(choices=[('general', '概况'), ('consult', '企业咨询'), ('science', '企业科技'), ('product', '企业产品'), ('relation', '企业联系'), ('forum', '企业论坛')], default='general', max_length=25, verbose_name='支付类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='company.CompanyCategory', verbose_name='当前类别的父级')),
            ],
            options={
                'verbose_name': '企业类别',
                'verbose_name_plural': '企业类别',
            },
        ),
        migrations.CreateModel(
            name='CompanyForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=66, null=True, verbose_name='论坛题目')),
                ('title_code', models.CharField(blank=True, max_length=66, null=True, verbose_name='论坛题目英文')),
                ('author', models.CharField(blank=True, max_length=66, null=True, verbose_name='作者姓名')),
                ('author_code', models.CharField(blank=True, max_length=66, null=True, verbose_name='作者姓名英文')),
                ('author_unit', models.CharField(blank=True, max_length=66, null=True, verbose_name='作者单位')),
                ('author_unit_code', models.CharField(blank=True, max_length=66, null=True, verbose_name='作者单位英文')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发表时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='company.CompanyCategory', verbose_name='类别')),
            ],
            options={
                'verbose_name': '论坛',
                'verbose_name_plural': '论坛',
            },
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='company/images/', verbose_name='图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_image', to='company.Company', verbose_name='企业')),
            ],
            options={
                'verbose_name': '企业图片',
                'verbose_name_plural': '企业图片',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.CompanyCategory', verbose_name='类别'),
        ),
    ]
