# Generated by Django 2.0 on 2019-11-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyimage',
            name='company',
        ),
        migrations.AddField(
            model_name='companyimage',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category_image', to='company.CompanyCategory', verbose_name='企业类别'),
        ),
    ]
