# Generated by Django 2.0 on 2019-11-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20191111_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyimage',
            options={'verbose_name': '企业类别图片', 'verbose_name_plural': '企业类别图片'},
        ),
    ]
